# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "svg-colors"
version = "0.1.0"
entrypoint = "src/svg-colors.typ"
authors = ["kleinbottle", "nandac"]
license = "Unlicense"
description = "Allows SVG named colors to be used directly in a Typst document "
# homepage = ""
repository = "https://github.com/kleinbottle/svg-colors"
keywords = ["named SVG colors"]
categories = ["components"]
disciplines = ["design", "drawing"]
compiler = "0.13.0"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
