#import "../src/css-colors.typ": css

#set page(margin: 25mm)
#set text(size: 11pt, font: "Noto Serif")

#align(center, text(size: 20pt)[SVG Colors Table])
#show table.cell.where(y: 0): smallcaps
#show table.cell.where(y: 0): strong
#align(center)[
  #table(
    inset: 10pt,
    columns: 4,
    stroke: none,
    align: (left+horizon, left+horizon, center+horizon, center+horizon),
    table.header([Name], [Hex Value], [Swatch], [Stripe]),
    [aliceblue], [#str("#f0f8ff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.aliceblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.aliceblue)],
    [antiquewhite], [#str("#faebd7")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.antiquewhite)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.antiquewhite)],
    [aqua], [#str("#00ffff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.aqua)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.aqua)],
    [aquamarine], [#str("#7fffd4")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.aquamarine)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.aquamarine)],
    [azure], [#str("#f0ffff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.azure)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.azure)],
    [beige], [#str("#f5f5dc")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.beige)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.beige)],
    [bisque], [#str("#ffe4c4")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.bisque)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.bisque)],
    [black], [#str("#000000")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.black)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.black)],
    [blanchedalmond], [#str("#ffebcd")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.blanchedalmond)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.blanchedalmond)],
    [blue], [#str("#0000ff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.blue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.blue)],
    [blueviolet], [#str("#8a2be2")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.blueviolet)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.blueviolet)],
    [brown], [#str("#a52a2a")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.brown)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.brown)],
    [burlywood], [#str("#deb887")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.burlywood)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.burlywood)],
    [cadetblue], [#str("#5f9ea0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.cadetblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.cadetblue)],
    [chartreuse], [#str("#7fff00")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.chartreuse)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.chartreuse)],
    [chocolate], [#str("#d2691e")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.chocolate)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.chocolate)],
    [coral], [#str("#ff7f50")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.coral)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.coral)],
    [cornflowerblue], [#str("#6495ed")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.cornflowerblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.cornflowerblue)],
    [cornsilk], [#str("#fff8dc")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.cornsilk)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.cornsilk)],
    [crimson], [#str("#dc143c")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.crimson)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.crimson)],
    [cyan], [#str("#00ffff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.cyan)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.cyan)],
    [darkblue], [#str("#00008b")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkblue)],
    [darkcyan], [#str("#008b8b")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkcyan)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkcyan)],
    [darkgoldenrod], [#str("#b8860b")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkgoldenrod)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkgoldenrod)],
    [darkgray], [#str("#a9a9a9")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkgray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkgray)],
    [darkgreen], [#str("#006400")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkgreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkgreen)],
    [darkgrey], [#str("#a9a9a9")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkgrey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkgrey)],
    [darkkhaki], [#str("#bdb76b")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkkhaki)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkkhaki)],
    [darkmagenta], [#str("#8b008b")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkmagenta)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkmagenta)],
    [darkolivegreen], [#str("#556b2f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkolivegreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkolivegreen)],
    [darkorange], [#str("#ff8c00")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkorange)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkorange)],
    [darkorchid], [#str("#9932cc")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkorchid)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkorchid)],
    [darkred], [#str("#8b0000")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkred)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkred)],
    [darksalmon], [#str("#e9967a")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darksalmon)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darksalmon)],
    [darkseagreen], [#str("#8fbc8f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkseagreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkseagreen)],
    [darkslateblue], [#str("#483d8b")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkslateblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkslateblue)],
    [darkslategray], [#str("#2f4f4f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkslategray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkslategray)],
    [darkslategrey], [#str("#2f4f4f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkslategrey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkslategrey)],
    [darkturquoise], [#str("#00ced1")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkturquoise)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkturquoise)],
    [darkviolet], [#str("#9400d3")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.darkviolet)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.darkviolet)],
    [deeppink], [#str("#ff1493")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.deeppink)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.deeppink)],
    [deepskyblue], [#str("#00bfff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.deepskyblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.deepskyblue)],
    [dimgray], [#str("#696969")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.dimgray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.dimgray)],
    [dimgrey], [#str("#696969")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.dimgrey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.dimgrey)],
    [dodgerblue], [#str("#1e90ff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.dodgerblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.dodgerblue)],
    [firebrick], [#str("#b22222")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.firebrick)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.firebrick)],
    [floralwhite], [#str("#fffaf0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.floralwhite)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.floralwhite)],
    [forestgreen], [#str("#228b22")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.forestgreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.forestgreen)],
    [fuchsia], [#str("#ff00ff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.fuchsia)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.fuchsia)],
    [gainsboro], [#str("#dcdcdc")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.gainsboro)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.gainsboro)],
    [ghostwhite], [#str("#f8f8ff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.ghostwhite)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.ghostwhite)],
    [gold], [#str("#ffd700")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.gold)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.gold)],
    [goldenrod], [#str("#daa520")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.goldenrod)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.goldenrod)],
    [gray], [#str("#808080")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.gray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.gray)],
    [green], [#str("#008000")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.green)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.green)],
    [greenyellow], [#str("#adff2f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.greenyellow)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.greenyellow)],
    [grey], [#str("#808080")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.grey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.grey)],
    [honeydew], [#str("#f0fff0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.honeydew)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.honeydew)],
    [hotpink], [#str("#ff69b4")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.hotpink)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.hotpink)],
    [indianred], [#str("#cd5c5c")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.indianred)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.indianred)],
    [indigo], [#str("#4b0082")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.indigo)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.indigo)],
    [ivory], [#str("#fffff0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.ivory)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.ivory)],
    [khaki], [#str("#f0e68c")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.khaki)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.khaki)],
    [lavender], [#str("#e6e6fa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lavender)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lavender)],
    [lavenderblush], [#str("#fff0f5")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lavenderblush)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lavenderblush)],
    [lawngreen], [#str("#7cfc00")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lawngreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lawngreen)],
    [lemonchiffon], [#str("#fffacd")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lemonchiffon)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lemonchiffon)],
    [lightblue], [#str("#add8e6")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightblue)],
    [lightcoral], [#str("#f08080")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightcoral)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightcoral)],
    [lightcyan], [#str("#e0ffff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightcyan)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightcyan)],
    [lightgoldenrodyellow], [#str("#fafad2")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightgoldenrodyellow)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightgoldenrodyellow)],
    [lightgray], [#str("#d3d3d3")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightgray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightgray)],
    [lightgreen], [#str("#90ee90")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightgreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightgreen)],
    [lightgrey], [#str("#d3d3d3")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightgrey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightgrey)],
    [lightpink], [#str("#ffb6c1")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightpink)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightpink)],
    [lightsalmon], [#str("#ffa07a")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightsalmon)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightsalmon)],
    [lightseagreen], [#str("#20b2aa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightseagreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightseagreen)],
    [lightskyblue], [#str("#87cefa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightskyblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightskyblue)],
    [lightslategray], [#str("#778899")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightslategray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightslategray)],
    [lightslategrey], [#str("#778899")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightslategrey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightslategrey)],
    [lightsteelblue], [#str("#b0c4de")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightsteelblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightsteelblue)],
    [lightyellow], [#str("#ffffe0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lightyellow)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lightyellow)],
    [lime], [#str("#00ff00")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.lime)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.lime)],
    [limegreen], [#str("#32cd32")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.limegreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.limegreen)],
    [linen], [#str("#faf0e6")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.linen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.linen)],
    [magenta], [#str("#ff00ff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.magenta)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.magenta)],
    [maroon], [#str("#800000")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.maroon)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.maroon)],
    [mediumaquamarine], [#str("#66cdaa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumaquamarine)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumaquamarine)],
    [mediumblue], [#str("#0000cd")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumblue)],
    [mediumorchid], [#str("#ba55d3")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumorchid)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumorchid)],
    [mediumpurple], [#str("#9370db")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumpurple)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumpurple)],
    [mediumseagreen], [#str("#3cb371")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumseagreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumseagreen)],
    [mediumslateblue], [#str("#7b68ee")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumslateblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumslateblue)],
    [mediumspringgreen], [#str("#00fa9a")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumspringgreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumspringgreen)],
    [mediumturquoise], [#str("#48d1cc")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumturquoise)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumturquoise)],
    [mediumvioletred], [#str("#c71585")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mediumvioletred)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mediumvioletred)],
    [midnightblue], [#str("#191970")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.midnightblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.midnightblue)],
    [mintcream], [#str("#f5fffa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mintcream)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mintcream)],
    [mistyrose], [#str("#ffe4e1")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.mistyrose)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.mistyrose)],
    [moccasin], [#str("#ffe4b5")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.moccasin)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.moccasin)],
    [navajowhite], [#str("#ffdead")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.navajowhite)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.navajowhite)],
    [navy], [#str("#000080")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.navy)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.navy)],
    [oldlace], [#str("#fdf5e6")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.oldlace)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.oldlace)],
    [olive], [#str("#808000")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.olive)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.olive)],
    [olivedrab], [#str("#6b8e23")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.olivedrab)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.olivedrab)],
    [orange], [#str("#ffa500")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.orange)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.orange)],
    [orangered], [#str("#ff4500")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.orangered)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.orangered)],
    [orchid], [#str("#da70d6")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.orchid)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.orchid)],
    [palegoldenrod], [#str("#eee8aa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.palegoldenrod)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.palegoldenrod)],
    [palegreen], [#str("#98fb98")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.palegreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.palegreen)],
    [paleturquoise], [#str("#afeeee")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.paleturquoise)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.paleturquoise)],
    [palevioletred], [#str("#db7093")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.palevioletred)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.palevioletred)],
    [papayawhip], [#str("#ffefd5")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.papayawhip)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.papayawhip)],
    [peachpuff], [#str("#ffdab9")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.peachpuff)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.peachpuff)],
    [peru], [#str("#cd853f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.peru)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.peru)],
    [pink], [#str("#ffc0cb")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.pink)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.pink)],
    [plum], [#str("#dda0dd")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.plum)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.plum)],
    [powderblue], [#str("#b0e0e6")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.powderblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.powderblue)],
    [purple], [#str("#800080")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.purple)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.purple)],
    [red], [#str("#ff0000")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.red)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.red)],
    [rosybrown], [#str("#bc8f8f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.rosybrown)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.rosybrown)],
    [royalblue], [#str("#4169e1")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.royalblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.royalblue)],
    [saddlebrown], [#str("#8b4513")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.saddlebrown)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.saddlebrown)],
    [salmon], [#str("#fa8072")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.salmon)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.salmon)],
    [sandybrown], [#str("#f4a460")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.sandybrown)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.sandybrown)],
    [seagreen], [#str("#2e8b57")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.seagreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.seagreen)],
    [seashell], [#str("#fff5ee")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.seashell)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.seashell)],
    [sienna], [#str("#a0522d")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.sienna)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.sienna)],
    [silver], [#str("#c0c0c0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.silver)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.silver)],
    [skyblue], [#str("#87ceeb")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.skyblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.skyblue)],
    [slateblue], [#str("#6a5acd")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.slateblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.slateblue)],
    [slategray], [#str("#708090")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.slategray)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.slategray)],
    [slategrey], [#str("#708090")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.slategrey)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.slategrey)],
    [snow], [#str("#fffafa")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.snow)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.snow)],
    [springgreen], [#str("#00ff7f")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.springgreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.springgreen)],
    [steelblue], [#str("#4682b4")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.steelblue)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.steelblue)],
    [tan], [#str("#d2b48c")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.tan)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.tan)],
    [teal], [#str("#008080")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.teal)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.teal)],
    [thistle], [#str("#d8bfd8")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.thistle)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.thistle)],
    [tomato], [#str("#ff6347")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.tomato)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.tomato)],
    [turquoise], [#str("#40e0d0")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.turquoise)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.turquoise)],
    [violet], [#str("#ee82ee")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.violet)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.violet)],
    [wheat], [#str("#f5deb3")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.wheat)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.wheat)],
    [white], [#str("#ffffff")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.white)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.white)],
    [whitesmoke], [#str("#f5f5f5")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.whitesmoke)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.whitesmoke)],
    [yellow], [#str("#ffff00")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.yellow)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.yellow)],
    [yellowgreen], [#str("#9acd32")], [#box(width: 1cm, height: 1cm, stroke: black, fill: svg.yellowgreen)], [#box(width: 5cm, height: 1cm, stroke: none, fill: svg.yellowgreen)],
  )
]
