#import "css-colors.typ": *

#set page(margin: 25mm)
#set text(size: 11pt, font: "Noto Serif")

#align(center, text(size: 20pt)[CSS Colors Table])
#show table.cell.where(y: 0): smallcaps
#show table.cell.where(y: 0): strong
#align(center)[
  #table(
    inset: 10pt,
    columns: 4,
    stroke: none,
    align: (left+horizon, left+horizon, center+horizon, center+horizon),
    table.header([Name], [Hex Value], [Swatch], [Stripe]),
    [aliceblue], [#get-hex-value("aliceblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("aliceblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("aliceblue"))],
    [antiquewhite], [#get-hex-value("antiquewhite")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("antiquewhite"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("antiquewhite"))],
    [aqua], [#get-hex-value("aqua")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("aqua"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("aqua"))],
    [aquamarine], [#get-hex-value("aquamarine")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("aquamarine"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("aquamarine"))],
    [azure], [#get-hex-value("azure")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("azure"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("azure"))],
    [beige], [#get-hex-value("beige")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("beige"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("beige"))],
    [bisque], [#get-hex-value("bisque")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("bisque"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("bisque"))],
    [black], [#get-hex-value("black")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("black"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("black"))],
    [blanchedalmond], [#get-hex-value("blanchedalmond")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("blanchedalmond"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("blanchedalmond"))],
    [blue], [#get-hex-value("blue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("blue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("blue"))],
    [blueviolet], [#get-hex-value("blueviolet")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("blueviolet"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("blueviolet"))],
    [brown], [#get-hex-value("brown")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("brown"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("brown"))],
    [burlywood], [#get-hex-value("burlywood")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("burlywood"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("burlywood"))],
    [cadetblue], [#get-hex-value("cadetblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("cadetblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("cadetblue"))],
    [chartreuse], [#get-hex-value("chartreuse")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("chartreuse"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("chartreuse"))],
    [chocolate], [#get-hex-value("chocolate")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("chocolate"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("chocolate"))],
    [coral], [#get-hex-value("coral")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("coral"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("coral"))],
    [cornflowerblue], [#get-hex-value("cornflowerblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("cornflowerblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("cornflowerblue"))],
    [cornsilk], [#get-hex-value("cornsilk")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("cornsilk"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("cornsilk"))],
    [crimson], [#get-hex-value("crimson")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("crimson"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("crimson"))],
    [cyan], [#get-hex-value("cyan")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("cyan"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("cyan"))],
    [darkblue], [#get-hex-value("darkblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkblue"))],
    [darkcyan], [#get-hex-value("darkcyan")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkcyan"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkcyan"))],
    [darkgoldenrod], [#get-hex-value("darkgoldenrod")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkgoldenrod"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkgoldenrod"))],
    [darkgray], [#get-hex-value("darkgray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkgray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkgray"))],
    [darkgreen], [#get-hex-value("darkgreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkgreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkgreen"))],
    [darkgrey], [#get-hex-value("darkgrey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkgrey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkgrey"))],
    [darkkhaki], [#get-hex-value("darkkhaki")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkkhaki"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkkhaki"))],
    [darkmagenta], [#get-hex-value("darkmagenta")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkmagenta"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkmagenta"))],
    [darkolivegreen], [#get-hex-value("darkolivegreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkolivegreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkolivegreen"))],
    [darkorange], [#get-hex-value("darkorange")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkorange"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkorange"))],
    [darkorchid], [#get-hex-value("darkorchid")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkorchid"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkorchid"))],
    [darkred], [#get-hex-value("darkred")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkred"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkred"))],
    [darksalmon], [#get-hex-value("darksalmon")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darksalmon"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darksalmon"))],
    [darkseagreen], [#get-hex-value("darkseagreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkseagreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkseagreen"))],
    [darkslateblue], [#get-hex-value("darkslateblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkslateblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkslateblue"))],
    [darkslategray], [#get-hex-value("darkslategray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkslategray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkslategray"))],
    [darkslategrey], [#get-hex-value("darkslategrey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkslategrey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkslategrey"))],
    [darkturquoise], [#get-hex-value("darkturquoise")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkturquoise"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkturquoise"))],
    [darkviolet], [#get-hex-value("darkviolet")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("darkviolet"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("darkviolet"))],
    [deeppink], [#get-hex-value("deeppink")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("deeppink"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("deeppink"))],
    [deepskyblue], [#get-hex-value("deepskyblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("deepskyblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("deepskyblue"))],
    [dimgray], [#get-hex-value("dimgray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("dimgray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("dimgray"))],
    [dimgrey], [#get-hex-value("dimgrey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("dimgrey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("dimgrey"))],
    [dodgerblue], [#get-hex-value("dodgerblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("dodgerblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("dodgerblue"))],
    [firebrick], [#get-hex-value("firebrick")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("firebrick"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("firebrick"))],
    [floralwhite], [#get-hex-value("floralwhite")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("floralwhite"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("floralwhite"))],
    [forestgreen], [#get-hex-value("forestgreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("forestgreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("forestgreen"))],
    [fuchsia], [#get-hex-value("fuchsia")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("fuchsia"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("fuchsia"))],
    [gainsboro], [#get-hex-value("gainsboro")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("gainsboro"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("gainsboro"))],
    [ghostwhite], [#get-hex-value("ghostwhite")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("ghostwhite"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("ghostwhite"))],
    [gold], [#get-hex-value("gold")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("gold"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("gold"))],
    [goldenrod], [#get-hex-value("goldenrod")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("goldenrod"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("goldenrod"))],
    [gray], [#get-hex-value("gray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("gray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("gray"))],
    [green], [#get-hex-value("green")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("green"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("green"))],
    [greenyellow], [#get-hex-value("greenyellow")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("greenyellow"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("greenyellow"))],
    [grey], [#get-hex-value("grey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("grey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("grey"))],
    [honeydew], [#get-hex-value("honeydew")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("honeydew"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("honeydew"))],
    [hotpink], [#get-hex-value("hotpink")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("hotpink"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("hotpink"))],
    [indianred], [#get-hex-value("indianred")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("indianred"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("indianred"))],
    [indigo], [#get-hex-value("indigo")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("indigo"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("indigo"))],
    [ivory], [#get-hex-value("ivory")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("ivory"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("ivory"))],
    [khaki], [#get-hex-value("khaki")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("khaki"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("khaki"))],
    [lavender], [#get-hex-value("lavender")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lavender"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lavender"))],
    [lavenderblush], [#get-hex-value("lavenderblush")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lavenderblush"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lavenderblush"))],
    [lawngreen], [#get-hex-value("lawngreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lawngreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lawngreen"))],
    [lemonchiffon], [#get-hex-value("lemonchiffon")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lemonchiffon"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lemonchiffon"))],
    [lightblue], [#get-hex-value("lightblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightblue"))],
    [lightcoral], [#get-hex-value("lightcoral")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightcoral"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightcoral"))],
    [lightcyan], [#get-hex-value("lightcyan")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightcyan"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightcyan"))],
    [lightgoldenrodyellow], [#get-hex-value("lightgoldenrodyellow")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightgoldenrodyellow"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightgoldenrodyellow"))],
    [lightgray], [#get-hex-value("lightgray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightgray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightgray"))],
    [lightgreen], [#get-hex-value("lightgreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightgreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightgreen"))],
    [lightgrey], [#get-hex-value("lightgrey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightgrey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightgrey"))],
    [lightpink], [#get-hex-value("lightpink")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightpink"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightpink"))],
    [lightsalmon], [#get-hex-value("lightsalmon")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightsalmon"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightsalmon"))],
    [lightseagreen], [#get-hex-value("lightseagreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightseagreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightseagreen"))],
    [lightskyblue], [#get-hex-value("lightskyblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightskyblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightskyblue"))],
    [lightslategray], [#get-hex-value("lightslategray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightslategray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightslategray"))],
    [lightslategrey], [#get-hex-value("lightslategrey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightslategrey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightslategrey"))],
    [lightsteelblue], [#get-hex-value("lightsteelblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightsteelblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightsteelblue"))],
    [lightyellow], [#get-hex-value("lightyellow")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lightyellow"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lightyellow"))],
    [lime], [#get-hex-value("lime")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("lime"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("lime"))],
    [limegreen], [#get-hex-value("limegreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("limegreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("limegreen"))],
    [linen], [#get-hex-value("linen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("linen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("linen"))],
    [magenta], [#get-hex-value("magenta")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("magenta"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("magenta"))],
    [maroon], [#get-hex-value("maroon")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("maroon"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("maroon"))],
    [mediumaquamarine], [#get-hex-value("mediumaquamarine")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumaquamarine"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumaquamarine"))],
    [mediumblue], [#get-hex-value("mediumblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumblue"))],
    [mediumorchid], [#get-hex-value("mediumorchid")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumorchid"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumorchid"))],
    [mediumpurple], [#get-hex-value("mediumpurple")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumpurple"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumpurple"))],
    [mediumseagreen], [#get-hex-value("mediumseagreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumseagreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumseagreen"))],
    [mediumslateblue], [#get-hex-value("mediumslateblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumslateblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumslateblue"))],
    [mediumspringgreen], [#get-hex-value("mediumspringgreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumspringgreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumspringgreen"))],
    [mediumturquoise], [#get-hex-value("mediumturquoise")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumturquoise"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumturquoise"))],
    [mediumvioletred], [#get-hex-value("mediumvioletred")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mediumvioletred"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mediumvioletred"))],
    [midnightblue], [#get-hex-value("midnightblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("midnightblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("midnightblue"))],
    [mintcream], [#get-hex-value("mintcream")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mintcream"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mintcream"))],
    [mistyrose], [#get-hex-value("mistyrose")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("mistyrose"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("mistyrose"))],
    [moccasin], [#get-hex-value("moccasin")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("moccasin"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("moccasin"))],
    [navajowhite], [#get-hex-value("navajowhite")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("navajowhite"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("navajowhite"))],
    [navy], [#get-hex-value("navy")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("navy"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("navy"))],
    [oldlace], [#get-hex-value("oldlace")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("oldlace"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("oldlace"))],
    [olive], [#get-hex-value("olive")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("olive"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("olive"))],
    [olivedrab], [#get-hex-value("olivedrab")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("olivedrab"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("olivedrab"))],
    [orange], [#get-hex-value("orange")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("orange"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("orange"))],
    [orangered], [#get-hex-value("orangered")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("orangered"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("orangered"))],
    [orchid], [#get-hex-value("orchid")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("orchid"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("orchid"))],
    [palegoldenrod], [#get-hex-value("palegoldenrod")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("palegoldenrod"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("palegoldenrod"))],
    [palegreen], [#get-hex-value("palegreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("palegreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("palegreen"))],
    [paleturquoise], [#get-hex-value("paleturquoise")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("paleturquoise"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("paleturquoise"))],
    [palevioletred], [#get-hex-value("palevioletred")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("palevioletred"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("palevioletred"))],
    [papayawhip], [#get-hex-value("papayawhip")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("papayawhip"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("papayawhip"))],
    [peachpuff], [#get-hex-value("peachpuff")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("peachpuff"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("peachpuff"))],
    [peru], [#get-hex-value("peru")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("peru"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("peru"))],
    [pink], [#get-hex-value("pink")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("pink"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("pink"))],
    [plum], [#get-hex-value("plum")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("plum"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("plum"))],
    [powderblue], [#get-hex-value("powderblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("powderblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("powderblue"))],
    [purple], [#get-hex-value("purple")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("purple"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("purple"))],
    [red], [#get-hex-value("red")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("red"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("red"))],
    [rosybrown], [#get-hex-value("rosybrown")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("rosybrown"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("rosybrown"))],
    [royalblue], [#get-hex-value("royalblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("royalblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("royalblue"))],
    [saddlebrown], [#get-hex-value("saddlebrown")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("saddlebrown"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("saddlebrown"))],
    [salmon], [#get-hex-value("salmon")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("salmon"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("salmon"))],
    [sandybrown], [#get-hex-value("sandybrown")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("sandybrown"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("sandybrown"))],
    [seagreen], [#get-hex-value("seagreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("seagreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("seagreen"))],
    [seashell], [#get-hex-value("seashell")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("seashell"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("seashell"))],
    [sienna], [#get-hex-value("sienna")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("sienna"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("sienna"))],
    [silver], [#get-hex-value("silver")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("silver"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("silver"))],
    [skyblue], [#get-hex-value("skyblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("skyblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("skyblue"))],
    [slateblue], [#get-hex-value("slateblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("slateblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("slateblue"))],
    [slategray], [#get-hex-value("slategray")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("slategray"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("slategray"))],
    [slategrey], [#get-hex-value("slategrey")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("slategrey"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("slategrey"))],
    [snow], [#get-hex-value("snow")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("snow"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("snow"))],
    [springgreen], [#get-hex-value("springgreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("springgreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("springgreen"))],
    [steelblue], [#get-hex-value("steelblue")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("steelblue"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("steelblue"))],
    [tan], [#get-hex-value("tan")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("tan"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("tan"))],
    [teal], [#get-hex-value("teal")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("teal"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("teal"))],
    [thistle], [#get-hex-value("thistle")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("thistle"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("thistle"))],
    [tomato], [#get-hex-value("tomato")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("tomato"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("tomato"))],
    [turquoise], [#get-hex-value("turquoise")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("turquoise"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("turquoise"))],
    [violet], [#get-hex-value("violet")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("violet"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("violet"))],
    [wheat], [#get-hex-value("wheat")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("wheat"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("wheat"))],
    [white], [#get-hex-value("white")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("white"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("white"))],
    [whitesmoke], [#get-hex-value("whitesmoke")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("whitesmoke"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("whitesmoke"))],
    [yellow], [#get-hex-value("yellow")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("yellow"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("yellow"))],
    [yellowgreen], [#get-hex-value("yellowgreen")], [#box(width: 1cm, height: 1cm, stroke: black,fill: css("yellowgreen"))], [#box(width: 5cm, height: 1cm, stroke: none,fill: css("yellowgreen"))],
  )
]
